### ISSUE TITLE
DM Error

### ISSUE THREAD

**Issue by UserBot29** [SilBoydens/raidbot#3]
An error has occoured:
          message: uncaughtException in global
Cannot read property 'raid' of undefined

          TypeError: Cannot read property 'raid' of undefined
    at checkPoint (/app/commandHandler.js:97:61)
    at Client.client.on.msg (/app/raidbot.js:100:8)
    at Client.emit (events.js:189:13)
    at MessageCreateHandler.handle (/rbd/pnpm-volume/3d97dcc3-e0a3-4fbc-8da2-10b4ba960397/node_modules/.registry.npmjs.org/discord.js/11.5.1/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/rbd/pnpm-volume/3d97dcc3-e0a3-4fbc-8da2-10b4ba960397/node_modules/.registry.npmjs.org/discord.js/11.5.1/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (/rbd/pnpm-volume/3d97dcc3-e0a3-4fbc-8da2-10b4ba960397/node_modules/.registry.npmjs.org/discord.js/11.5.1/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/rbd/pnpm-volume/3d97dcc3-e0a3-4fbc-8da2-10b4ba960397/node_modules/.registry.npmjs.org/discord.js/11.5.1/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/rbd/pnpm-volume/3d97dcc3-e0a3-4fbc-8da2-10b4ba960397/node_modules/.registry.npmjs.org/ws/6.2.1/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:189:13)
    at Receiver.receiverOnMessage (/rbd/pnpm-volume/3d97dcc3-e0a3-4fbc-8da2-10b4ba960397/node_modules/.registry.npmjs.org/ws/6.2.1/node_modules/ws/lib/websocket.js:789:20)

**Comment by Alirezarfe** [comment]
this will no longer an issue in the rewrite
